version: "3"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    command: '-N 500'
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "phoenix_starter_dev"
    ports:
      - 5432:5432

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "7001:80"
    volumes:
      - ./docker-compose-configs/pg-admin.json:/pgadmin4/servers.json
